project:
  type: website
  output-dir: docs 
  preview:
    port: 314

format:
  html:
    code-copy: true 
    code-overflow: wrap
    code-fold: false
    code-tools: false
    code-line-numbers: true
    # code-summary: "Show the code"
    # smooth-scroll: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full

website:
  title: "DSS R BootCamp"
  favicon: website_thumbnail.png
  repo-url: https://github.com/BrighamEaquinto/brighameaquinto.github.io.git
  # repo-actions: [edit, issue]
  page-navigation: true

  navbar:
    background: primary
    # logo: website_thumbnail.jpg
    pinned: true
    title: false
    # collapse: false
    collapse-below: md
    left: 
      - text: "DSS Bootcamp"
        href: main.qmd
      - text: "Installation"
        href: "lessons/lesson1_intro.qmd"
      - text: "Reading Data"
        href: "lessons/lesson2_readr.qmd"
      - text: "Wrangling Data"
        menu: 
        - text: "Lesson 3"
          href: "lessons/lesson3_dplyr.qmd"
        - text: "Lesson 4"
          href: "lessons/lesson4_dplyr.qmd"
      - text: "Visualizing Data"
        menu: 
          - text: "Lesson 5"
            href: "lessons/lesson5_ggplot.qmd"
          - text: "Lesson 6"
            href: "lessons/lesson6_ggplot.qmd"
      - text: "Other"
        menu: 
        - text: "Dax" 
          href: "other/dax/dax.qmd"
        - text: "Welcome"
          href: "other/welcome/welcome.qmd"



  page-footer: 
    left: 
      - icon: github
        href: https://github.com/BrighamEaquinto
      - icon: linkedin
        href: https://www.linkedin.com/in/brighameaquinto/
    background: secondary


