project:
  type: website
  output-dir: docs 
  preview:
    port: 314

format:
  html:
    code-copy: true 
    code-overflow: wrap
    code-fold: false
    code-tools: false
    code-line-numbers: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full

website:
  title: "DSS R BootCamp"
  favicon: pictures\website_thumbnail.png
  repo-url: https://github.com/BrighamEaquinto/brighameaquinto.github.io.git
  # repo-actions: [edit, issue]
  page-navigation: true

  navbar:
    background: primary
    # logo: pictures\website_thumbnail.png
    pinned: true
    title: false
    # collapse: false
    collapse-below: sm
    left: 
      - text: "DSS Bootcamp"
        href: index.qmd
      - text: "Installation"
        href: lessons/lesson1_intro.qmd
      - text: "Reading Data"
        href: lessons\lesson2_readr.qmd
      - text: "Wrangling Data"
        menu: 
        - text: "Wrangling Part 1"
          href: lessons\lesson3_dplyr.qmd
        - text: "Wrangling Part 2"
          href: lessons\lesson4_dplyr.qmd
      - text: "Visualizing Data"
        menu: 
          - text: "Visualizing Part 1"
            href: lessons\lesson5_ggplot.qmd
          - text: "Visualizing Part 2"
            href: lessons\lesson6_ggplot.qmd
      - text: Final Practice
        href: lessons\all_together.qmd
      # - text: "Other"
      #   menu: 
      #   - text: "Dax" 
      #     href: other\dax\dax.qmd
      #   - text: "Welcome"
      #     href: other\welcome\welcome.qmd

  page-footer: 
    left: 
      - icon: github
        href: https://github.com/BrighamEaquinto
      - icon: linkedin
        href: https://www.linkedin.com/in/brighameaquinto/
    background: secondary


