project:
  type: website
  output-dir: docs 
  preview:
    port: 314

format:
  html:
    code-copy: true 
    code-overflow: scroll
    code-fold: false
    code-tools: false
    code-line-numbers: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full
    title-block-banner: false
    # title-block-banner-color: green # this changes the color of the title of the website
    title-block-categories: true
    title-block-style: default
    # title-prefix: hey # 

website:
  title: "DSS R BootCamp"
  favicon: images/website_thumbnail.png
  repo-url: https://github.com/BrighamEaquinto/brighameaquinto.github.io.git
  # repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    background: primary
    logo: images/website_thumbnail.png
    pinned: true
    # title: false
    # collapse: false
    collapse-below: lg
    left: 
      - text: "Installation"
        href: lessons/lesson1_intro.qmd
      - text: "Reading Data"
        href: lessons/lesson2_readr.qmd
      - text: "Wrangling Data"
        menu: 
        - text: "Wrangling Part 1"
          href: lessons/lesson3_dplyr.qmd
        - text: "Wrangling Part 2"
          href: lessons/lesson4_dplyr.qmd
      - text: "Visualizing Data"
        menu: 
          - text: "Visualizing Part 1"
            href: lessons/lesson5_ggplot.qmd
          - text: "Visualizing Part 2"
            href: lessons/lesson6_ggplot.qmd
      - text: Extras
        menu: 
          - text: Practice 1
            href: lessons/extra/lesson7_practice.qmd
          - text: R or Python?
            href: lessons/extra/lesson8_python.qmd 
  page-footer: 
    left: 
      - icon: github
        href: https://github.com/BrighamEaquinto
      - icon: linkedin
        href: https://www.linkedin.com/in/brighameaquinto/
    background: secondary