project:
  type: website
  output-dir: docs
  preview:
    port: 314

website:
  title: "DSS BootCamp"
  image: website_thumbnail.jpg
  repo-url: https://github.com/BrighamEaquinto/brighameaquinto.github.io.git
  repo-actions: [edit, issue]
  navbar:
    background: primary
    pinned: true
  sidebar:
    # title: "Tutorials"
    style: "docked"
    search: true
    background: light
    collapse-level: 2
    contents: 
      - posts\Reading Data\index.qmd
      - posts\Wrangling Data\index.qmd
      - posts\Visualize Data\index.qmd
  page-footer: 
    left: 
      - icon: github
        href: https://github.com/BrighamEaquinto
      - icon: linkedin
        href: https://www.linkedin.com/in/brighameaquinto/
    background: secondary
format:
  html:
    code-copy: true 
    code-overflow: wrap
    code-fold: show
    code-tools: true
    code-summary: "Show the code"
    smooth-scroll: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css




