project:
  type: website
  output-dir: docs 
  preview:
    port: 314

format:
  html:
    code-copy: true 
    code-overflow: wrap
    code-fold: false
    code-tools: false
    # code-summary: "Show the code"
    # smooth-scroll: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full

website:
  title: "DSS R BootCamp"
  favicon: website_thumbnail.png
  repo-url: https://github.com/BrighamEaquinto/brighameaquinto.github.io.git
  repo-actions: [edit, issue]
  page-navigation: true

  navbar:
    background: primary
    # logo: website_thumbnail.jpg
    pinned: true
    title: false
    # collapse: false
    collapse-below: md
    left: 
      - text: "DSS Bootcamp"
        href: main.qmd
      - text: "Install R & RStudio"
        href: posts\Installation\installation.qmd
      - text: "Reading Data"
        href: posts\Reading Data\reading_data.qmd
      - text: "Wrangling Data"
        href: posts\Wrangling Data\wrangling_data.qmd
      - text: "Visualizing Data"
        href: posts\Visualize Data\visualizing_data.qmd
      - text: "Weeks"
        menu: 
        - text: "Lesson 1: Installation to Data Science" 
          href: "posts/Installation/installation.qmd"
        - text: "Lesson 2: Reading Data" 
          href: "posts/weeks/Oct_12th.qmd"
        - text: "Lesson 3: Wangling Data: First Four Verbs (Select, Filter, Mutate, Arrange"
          href: "posts/lessons/lesson4_dplyr.qmd"
        - text: "Lesson 4: Wrangling Data: Last 2 Verbs (Grouping, Summarising, and Arranging)"
          href: "posts/lessons/lesson4_dplyr.qmd"
        - text: "Lesson 5: Graphing 1/2"
          href: "posts/lessons/lesson5_ggplot.qmd"
        - text: "Lesson 6: Graphing 2/2"
          href: "posts/lessons/lesson6_ggplot.qmd"

  # sidebar:
  #   # title: "Tutorials"
  #   style: "docked"
  #   search: true
  #   background: light
  #   collapse-level: 2

  page-footer: 
    left: 
      - icon: github
        href: https://github.com/BrighamEaquinto
      - icon: linkedin
        href: https://www.linkedin.com/in/brighameaquinto/
    background: secondary


