project:
  type: website
  output-dir: docs 
  preview:
    port: 314

format:
  html:
    code-copy: true 
    code-overflow: wrap
    code-fold: false
    code-tools: false
    # code-summary: "Show the code"
    # smooth-scroll: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full

website:
  title: "DSS R BootCamp"
  image: website_thumbnail.png
  repo-url: https://github.com/BrighamEaquinto/brighameaquinto.github.io.git
  repo-actions: [edit, issue]
  page-navigation: true

  navbar:
    background: primary
    # logo: website_thumbnail.jpg
    pinned: true
    title: false
    # collapse: false
    collapse-below: md
    left: 
      - text: "DSS Bootcamp"
        href: main.qmd
      - text: "Install R & RStudio"
        href: posts\Installation\installation.qmd
      - text: "Reading Data"
        href: posts\Reading Data\reading_data.qmd
      - text: "Wrangling Data"
        href: posts\Wrangling Data\wrangling_data.qmd
      - text: "Visualizing Data"
        href: posts\Visualize Data\visualizing_data.qmd
      - text: "Weeks"
        menu: 
        - text: "Week 2 (Oct 5th)"
          href: posts/weeks/Oct_5th.qmd
        - text: "Week 3 (Oct 12th)"
          href: posts/weeks/Oct_12th.qmd
        - text: "Week 4 (Oct 12th)"
          href: posts/weeks/Oct_19th.qmd

  # sidebar:
  #   # title: "Tutorials"
  #   style: "docked"
  #   search: true
  #   background: light
  #   collapse-level: 2

  page-footer: 
    left: 
      - icon: github
        href: https://github.com/BrighamEaquinto
      - icon: linkedin
        href: https://www.linkedin.com/in/brighameaquinto/
    background: secondary


